# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinkcom', '0002_site_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoot',
            name='exists',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
